# render.yaml  –  minimal & valid
services:
  - type: cron
    name: drive-uploader
    env: python
    schedule: "0 8 * * *"           # 08:00 UTC daily
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python upload.py"
    envVars:
      - key: DRIVE_FOLDER_ID        # add the real value in the dashboard
        sync: false
      - key: CSV_NAME               # optional override (defaults to dataset.csv)
        value: ""
      - key: SERVICE_ACCOUNT_FILE   # tell the script where the key will mount
        value: /etc/secrets/service_account.json